name: lockerroom
description: A basketball stats application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: 3.2.0

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  google_fonts: 4.0.4
  hexcolor: 3.0.1
  http: 0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.jpg